### ISSUE TITLE
分离出 CpdailyCore 库

### ISSUE THREAD

**Issue by cyanray** [cyanray/cpdaily-auto-submit#2]
疫苗出来了（早就出来了），春天要到了，新冠迟早药丸。

新冠的自动填报估计很快就成为历史了。

但是今日校园还是有很多好玩的功能，可以做成机器人之类的小玩意，服务师生。

分离出 CpdailyCore 库，可以有助于学生开发者开发第三方的有关今日校园的程序。

**Comment by wxyttty** [comment]
很快估计是不行的，疫苗还在分批接种，间隔28天，全面接种完，也快入夏了吧。而且新冠可能会像流感一样长期存在，不像非典一样到了时间就过去了，现在的疫苗概率才70，还是不够啊。

**Comment by cyanray** [comment]
> 很快估计是不行的，疫苗还在分批接种，间隔28天，全面接种完，也快入夏了吧。而且新冠可能会像流感一样长期存在，不像非典一样到了时间就过去了，现在的疫苗概率才70，还是不够啊。

你说对了，我们又要开始填今日校园。这疫情反反复复……

**Comment by cyanray** [comment]
https://github.com/cyanray/CpdailyClient
